### ISSUE TITLE
Pop-up menu closes too fast for wrist/hands

### ISSUE THREAD

**Issue by drippyb** [mcd8604/wowengraver#10]
The wrist/Hands pop-up menu closes when my cursor is in-between the current rune and the pop-up menu.  Other slots are fine.  Video of issue below

https://github.com/mcd8604/wowengraver/assets/157657439/8525d419-987f-4f51-bf0d-9d840b3c885c

**Comment by mcd8604** [comment]
![image](https://github.com/mcd8604/wowengraver/assets/2568468/c4cd2669-ab2e-4bc5-ad7d-593447cc3b35)
There is another addon which is stealing the mouse because it is actually on top of the Engraver.
Use /fstack in game then hover over this area and you will see something like this but with another addon also listed:
![image](https://github.com/mcd8604/wowengraver/assets/2568468/804a407c-4100-44cf-88e6-dec5c7137216)
